/**
 * src/features/tailoring/index.ts
 */
export {
  useActiveGarmentTypes,
  useMeasurementTemplates,
  useActiveProductionStages,
  useMeasurementProfiles,
  useCaptureMeasurements,
  useSubmitInquiry,
  useMyTailoringRequests,
  useTailoringRequestsForStaff,
  useTailoringRequestDetail,
  useRequestStatusHistory,
  useAdvanceTailoringRequestStatus,
  useAssignTailoringRequest,
  useAppointmentsForRequest,
  useScheduleAppointment,
  useUpdateAppointmentStatus,
  useFabricSelection,
  useSubmitFabricSelection,
  useDesignBrief,
  useSubmitOrUpdateDesignBrief,
  useReferenceImages,
  useAddReferenceImage,
  useQuotationsForRequest,
  useCreateQuotation,
  useSendQuotation,
  useAcceptQuotation,
  useRejectQuotation,
  useCurrentStage,
  useStageHistory,
  useAdvanceProductionStage,
} from './tailoring.hooks';

export {
  listActiveGarmentTypes,
  listMeasurementTemplates,
  listActiveProductionStages,
  listMeasurementProfiles,
  captureMeasurements,
  submitInquiry,
  listMyTailoringRequests,
  listTailoringRequestsForStaff,
  getTailoringRequestDetail,
  listRequestStatusHistory,
  advanceTailoringRequestStatus,
  assignTailoringRequest,
  listAppointmentsForRequest,
  scheduleAppointment,
  updateAppointmentStatus,
  getFabricSelection,
  submitFabricSelection,
  getDesignBrief,
  submitOrUpdateDesignBrief,
  listReferenceImages,
  addReferenceImage,
  listQuotationsForRequest,
  createQuotation,
  sendQuotation,
  acceptQuotation,
  rejectQuotation,
  getCurrentStage,
  listStageHistory,
  advanceProductionStage,
} from './tailoring.service';

export { tailoringQueryKeys } from './tailoring.queryKeys';

export type {
  GarmentType,
  GarmentMeasurementTemplate,
  MeasurementField,
  MeasurementProfile,
  TailoringRequest,
  TailoringRequestDetail,
  Appointment,
  FabricSelection,
  DesignBrief,
  ReferenceImage,
  Quotation,
  QuotationLineItem,
  ProductionStage,
  StageHistoryEntry,
  RequestStatusHistoryEntry,
  SubmitInquiryInput,
  ScheduleAppointmentInput,
  SubmitFabricSelectionInput,
  SubmitDesignBriefInput,
  AddReferenceImageInput,
  CaptureMeasurementsInput,
  CreateQuotationInput,
  AdvanceProductionStageInput,
} from './tailoring.types';

export { TailoringError } from './tailoring.errors';
export type { TailoringErrorCode } from './tailoring.errors';
