/**
 * src/features/order/index.ts
 */
export {
  useCheckout,
  useCancelOrder,
  useAdvanceOrderStatus,
  useMyOrders,
  useOrdersForStaff,
  useOrderDetail,
  useOrderStatusHistory,
  usePaymentsForOrder,
  usePaymentTransactions,
  useShipmentsForOrder,
  useCreateShipment,
  useUpdateShipmentStatus,
  useShipmentTrackingEvents,
  useCoupons,
  useCreateCoupon,
  useDeactivateCoupon,
  useValidateCoupon,
  usePromotions,
  useCreatePromotion,
  useActiveTaxRules,
  useInvoiceForOrder,
  useGenerateInvoice,
  useMyReturnRequests,
  useRequestReturn,
  useAdvanceReturnRequestStatus,
  useIssueRefund,
  useMarkRefundProcessed,
} from './order.hooks';

export {
  checkout,
  cancelOrder,
  advanceOrderStatus,
  listMyOrders,
  listOrdersForStaff,
  getOrderDetail,
  listOrderStatusHistory,
  listPaymentsForOrder,
  listPaymentTransactions,
  listShipmentsForOrder,
  createShipment,
  updateShipmentStatus,
  listShipmentTrackingEvents,
  listCoupons,
  createCoupon,
  deactivateCoupon,
  validateCoupon,
  listPromotions,
  createPromotion,
  listActiveTaxRules,
  getInvoiceForOrder,
  generateInvoiceForOrder,
  listMyReturnRequests,
  requestReturn,
  advanceReturnRequestStatus,
  issueRefund,
  markRefundProcessed,
} from './order.service';

export { orderQueryKeys } from './order.queryKeys';

export type {
  Order,
  OrderItem,
  OrderSummary,
  StaffOrderSummary,
  OrderDetail,
  Payment,
  PaymentTransaction,
  Shipment,
  ShipmentTrackingEvent,
  Coupon,
  CouponValidation,
  Promotion,
  TaxRule,
  Invoice,
  Refund,
  RefundItem,
  OrderStatusHistoryEntry,
  ReturnRequest,
  CheckoutInput,
  CancelOrderInput,
  CreateShipmentInput,
  UpdateShipmentStatusInput,
  RequestReturnInput,
  IssueRefundInput,
  CreateCouponInput,
  CreatePromotionInput,
} from './order.types';

export { OrderError } from './order.errors';
export type { OrderErrorCode } from './order.errors';
