/**
 * src/features/cms/index.ts
 */
export {
  useRegisterMediaAsset,
  useActivePages,
  usePageByKey,
  usePublishedContentBlocks,
  useContentBlocksForStaff,
  useCreateContentBlock,
  useUpdateContentBlockContent,
  usePublishContentBlock,
  useUnpublishContentBlock,
  useActiveHeroBanners,
  useCreateHeroBanner,
  usePublishHeroBanner,
  useUnpublishHeroBanner,
  useFeaturedPlacements,
  useAddFeaturedPlacement,
  useRemoveFeaturedPlacement,
  usePublishedGalleryItems,
  useAddGalleryItem,
  useSetGalleryItemStatus,
  usePublishedTestimonials,
  useAddTestimonial,
  useSetTestimonialStatus,
  useActiveAnnouncements,
  useCreateAnnouncement,
  useSetAnnouncementStatus,
  useNavigationMenuByKey,
  useNavigationTree,
  useCreateNavigationItem,
  useSetMegaMenuPromo,
  usePublishedSocialLinks,
  useAddSocialLink,
  useContactInfo,
  useUpdateContactInfo,
  useResolveSeoRedirect,
  useCreateSeoRedirect,
  usePublicSiteSettings,
  useSiteSetting,
  useSetSiteSetting,
} from './cms.hooks';

export {
  registerMediaAsset,
  listActivePages,
  getPageByKey,
  listPublishedContentBlocks,
  listContentBlocksForStaff,
  createContentBlock,
  updateContentBlockContent,
  publishContentBlock,
  unpublishContentBlock,
  listActiveHeroBanners,
  createHeroBanner,
  publishHeroBanner,
  unpublishHeroBanner,
  listFeaturedPlacements,
  addFeaturedPlacement,
  removeFeaturedPlacement,
  listPublishedGalleryItems,
  addGalleryItem,
  setGalleryItemStatus,
  listPublishedTestimonials,
  addTestimonial,
  setTestimonialStatus,
  listActiveAnnouncements,
  createAnnouncement,
  setAnnouncementStatus,
  getNavigationMenuByKey,
  getNavigationTree,
  createNavigationItem,
  setMegaMenuPromo,
  listPublishedSocialLinks,
  addSocialLink,
  getContactInfo,
  updateContactInfo,
  resolveSeoRedirect,
  createSeoRedirect,
  listPublicSiteSettings,
  getSiteSetting,
  setSiteSetting,
} from './cms.service';

export { cmsQueryKeys } from './cms.queryKeys';

export type {
  MediaAsset,
  Page,
  ContentBlock,
  HeroBanner,
  FeaturedPlacement,
  PlacementContext,
  PlacementType,
  GalleryItem,
  Testimonial,
  Announcement,
  NavigationMenu,
  NavigationItem,
  NavigationTreeNode,
  MegaMenuPromo,
  SocialLink,
  ContactInfo,
  SeoRedirect,
  SiteSetting,
  RegisterMediaAssetInput,
  CreateContentBlockInput,
  UpdateContentBlockContentInput,
  CreateHeroBannerInput,
  CreateFeaturedPlacementInput,
  CreateGalleryItemInput,
  CreateTestimonialInput,
  CreateAnnouncementInput,
  CreateNavigationItemInput,
  SetMegaMenuPromoInput,
  CreateSocialLinkInput,
  UpdateContactInfoInput,
  CreateSeoRedirectInput,
} from './cms.types';

export { CmsError } from './cms.errors';
export type { CmsErrorCode } from './cms.errors';
